[Update] Enable Publishing to FIFO Topic
Orange-Health/pubsublib pull request #15
Opened 2024-02-03 15:21 UTC by gmmanu

## Summary
- Support for publishing messages to FIFO SNS topics

2024-02-05 02:40 UTC, CariappaKGanapathi approved these changes
LGTM! While consuming, you will have to handle cases where the body is put in redis as well

2024-02-05 04:50 UTC, CariappaKGanapathi requested changes
Duplicate function, you can add messageGroupId to the above Publish function and pass empty in places that it is not needed.

2024-02-06 16:50 UTC, CariappaKGanapathi approved these changes
LGTM!

2024-02-13 12:28 UTC, raj-nt approved these changes

2024-02-13 12:28 UTC, merged